const SUPABASE_URL = 'https://rhkedarsakcqkwukxpcz.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoa2VkYXJzYWtjcWt3dWt4cGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3NDgzNjEsImV4cCI6MjEwNDMyNDM2MX0.F2TY87YeWgP7tVsD-YbO9UqXUaHxPAw138t1xr7VuMA';

window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);